# Generated by Django 4.2.2 on 2023-06-13 23:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('login', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('role', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('target_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('users', models.ManyToManyField(related_name='targets', to='geo_base.user')),
            ],
        ),
    ]
