# Generated by Django 4.2.2 on 2023-06-16 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo_base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='target',
            old_name='target_id',
            new_name='id',
        ),
    ]
