# Generated by Django 4.2.2 on 2023-06-21 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo_base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='comment',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
