# Generated by Django 4.2.2 on 2023-06-14 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo_base', '0002_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(default='Agent'),
        ),
    ]
