# Generated by Django 4.2.2 on 2023-07-09 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo_base', '0003_delete_meta_alter_target_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='target',
            options={},
        ),
    ]
